version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"
  invoiceapi:
    image: ${DOCKER_REGISTRY-}invoiceapi
    build:
      context: .
      dockerfile: src/InvoiceAPI/Dockerfile
    links:
        - mongo 
